AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
