version: "3"

services:
  base: &base
    build:
      context: .
      cache_from:
        - rails6api-development-cache
    image: rails6api-development:0.1.0
    tmpfs:
      - /tmp
    env_file: .env

  db:
    image: postgres:11.5-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.8-alpine
    command: redis-server
    ports:
      - "6379:6379"
  sidekiq:
    <<: *base
    volumes:
      - .:/bikeramp/src
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
  web:
    <<: *base
    entrypoint: /bikeramp/src/docker-compose/web-entrypoint.sh
    build:
      context: .
      args:
        # Install development and test gems
        BUNDLE_WITHOUT: ""
        # Setup container user and group ids to match the host user
        APP_USER_ID: "${USER_ID:-1000}"
        APP_GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - .:/bikeramp/src
      - bundle_cache:/bikeramp/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    command: ["./wait-for-postgres.sh", "db", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]


volumes:
  bundle_cache:
  db_data:
